import json, os, numpy as np
O = '/mnt/user-data/outputs'
N = ['Base', '+Stats', '+HI', '+Weibull', '+Entropy', '+ExpDeg', '+LG']

def L(f):
    return json.load(open(os.path.join(O, f)))
fd1 = L('results_cmapss.json')
_full = json.load(open(os.path.join(O, 'results_full_FD003.json'))) if os.path.exists(os.path.join(O, 'results_full_FD003.json')) else None
fd3 = {n: _full['table'][n]['test'] for n in N} if _full else {n: L('results_cmapss_fd.json')['FD003_fast'][n]['test'] for n in N}
az = L('results_azure.json')
azc = [c for c in az if isinstance(az[c], dict)]
bt = L('results_battery.json')['cv']
col = {'fd1': {n: fd1[n]['c'] for n in N}, 'fd3': {n: fd3[n] for n in N}, 'az': {n: float(np.mean([az[c][n]['test'] for c in azc])) for n in N}, 'bt': {n: bt[n]['mean'] for n in N}, 'bts': {n: bt[n]['std'] for n in N}}
lead = {k: max(N, key=lambda n: col[k][n]) for k in ['fd1', 'fd3', 'az', 'bt']}

def cell(k, n, std=None, dec=3):
    v = col[k][n]
    s = f'{v:.{dec}f}' if std is None else f'{v:.{dec}f}\\,$\\pm$\\,{col[std][n]:.{dec}f}'
    return f'\\textbf{{{s}}}' if n == lead[k] else s
rows = '\n'.join((f'  {n:<9} & {cell('fd1', n, dec=4)} & {cell('fd3', n, dec=4)} & {cell('az', n)} & {cell('bt', n, 'bts')} \\\\' for n in N))
bo = _full['bootstrap'] if _full else L('results_bootstrap_FD003.json')
ciN = '\n'.join((f'  {n:<9} & {bo['point'][n]:.3f} & [{bo['ci'][n][0]:.3f}, {bo['ci'][n][1]:.3f}] \\\\' for n in N if n in bo['ci']))
order = ['+LG-+ExpDeg', '+LG-Base', '+ExpDeg-Base', '+HI-Base', '+Weibull-Base', '+Entropy-Base', '+Stats-Base']
diffrows = '\n'.join((f'  {k.replace('-', ' $-$ '):<22} & {bo['diff'][k]['point']:+.4f} & [{bo['diff'][k]['ci'][0]:+.4f}, {bo['diff'][k]['ci'][1]:+.4f}] & {('sig.' if bo['diff'][k]['sig'] else 'n.s.')} \\\\' for k in order if k in bo['diff']))
tex = '% master_table.tex — generated by master_table.py from results_*.json\n% NOTE: FD001 = full reproduction; FD003 = sub-sampled training (ranking, not\n% absolute -- re-run at full settings); Azure = mean over 4 components;\n% Battery = leave-one-cell-out CV (mean $\\pm$ std). Bootstrap CIs use FULL data.\n\\begin{table}[!t]\n\\centering\n\\caption{Test C-index by feature paradigm under the shared GBSA learner, across\ndatasets. Bold marks the per-dataset leader; C-MAPSS columns are reported to four\ndecimals to resolve the closely spaced paradigms. On FD001 the LG map attains the\nhighest C-index ($0.8317$ vs.\\ $0.8316$ for ExpDeg), but the two remain within the\nnoise band on every dataset; the generic-telemetry (Azure) and age-driven\n(battery, Weibull) cases are led by other paradigms.}\n\\label{tab:master}\n\\footnotesize\n\\begin{tabular}{lcccc}\n\\toprule\n & \\multicolumn{2}{c}{C-MAPSS} & Azure & NASA \\\\\n\\cmidrule(lr){2-3}\nParadigm & FD001 & FD003 & PdM$^{\\dagger}$ & battery$^{\\S}$ \\\\\n\\midrule\n' + rows + '\n\\bottomrule\n\\end{tabular}\n\n\\vspace{2pt}\n\\raggedright\\scriptsize\n$^{\\dagger}$mean over 4 components. $^{\\S}$leave-one-cell-out CV, mean $\\pm$ std.\n\\end{table}\n\n\\begin{table}[!t]\n\\centering\n\\caption{Cluster bootstrap (2000 resamples over the 20 test engines) on C-MAPSS\nFD003 (full training). Top: per-paradigm 95\\% CI. Bottom: paired differences (same resampled\nengines for both models); a CI excluding 0 is significant. The LG$-$ExpDeg gap\nis $\\sim$0.001 in C-index---statistically detectable but practically\nnegligible, i.e.\\ the two paradigms are equivalent predictors.}\n\\label{tab:bootstrap}\n\\footnotesize\n\\begin{tabular}{lcc}\n\\toprule\nParadigm & C-index & 95\\% CI \\\\\n\\midrule\n' + ciN + '\n\\midrule\n\\multicolumn{3}{l}{\\textit{Paired differences}} \\\\\n\\midrule\n\\end{tabular}\n\\begin{tabular}{lccc}\nComparison & $\\Delta$C & 95\\% CI & \\\\\n\\midrule\n' + diffrows + '\n\\bottomrule\n\\end{tabular}\n\\end{table}\n'
open(os.path.join(O, 'lg-piml/paper_patch/master_table.tex'), 'w').write(tex)
print('escrito master_table.tex')
print('leaders:', lead)